###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "Chakyll Calderon",
  "password": 201196,
  "email": "chakyllfcu@gmail.com",
  "status": 1
}

###
POST http://localhost:9000/api/punches HTTP/1.1
Content-Type: application/json

{
  "entryDate": "2023-11-24T8:56:43.512Z",
  "userId": "656021df59f5a8dac80dbf2e",
  "outDate": "2023-11-24T12:58:43.511Z",
  "status": 1
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/6560200db9f9053ac3f20a10 HTTP/1.1

###
DELETE http://localhost:9000/api/users/6560200db9f9053ac3f20a10 HTTP/1.1

###
PUT http://localhost:9000/api/users/6137e2412e329eb206b0073c HTTP/1.1
Content-Type: application/json

{
  "name": "John Conway",
  "age": 80,
  "email": "johnconway@email.com"
}

###
PUT http://localhost:9000/api/punches/65651fc02cb84c38c3280e0a HTTP/1.1
Content-Type: application/json
{
    "entryDate": "2023-11-24T8:56:43.512Z",
    "userId": "656021df59f5a8dac80dbf2e",
    "outDate": "2023-11-24T12:58:43.511Z",
    "status": 1
}